"""Ip 4th Sem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7I-iiAYUnRvEcUxKuNvmuV1wveXJxxR
"""

"""# Step 1 — Load dataset"""

import pandas as pd

df = pd.read_csv("data_core.csv")

print(df.head())
print(df.columns)
print(df.shape)

"""# Step 2 — Data preprocessing"""

from sklearn.preprocessing import LabelEncoder

soil_encoder = LabelEncoder()
crop_encoder = LabelEncoder()
fert_encoder = LabelEncoder()

df['Soil_Type_Enc'] = soil_encoder.fit_transform(df['Soil Type'])
df['Crop_Enc'] = crop_encoder.fit_transform(df['Crop Type'])
df['Fert_Enc'] = fert_encoder.fit_transform(df['Fertilizer Name'])

"""# Step 3 — Model 1 (Soil ➜ Nutrients)"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import joblib

X_nutrient = df[['Temparature','Humidity','Moisture','Soil_Type_Enc']]
y_nutrient = df[['Nitrogen','Phosphorous','Potassium']]

X_train, X_test, y_train, y_test = train_test_split(
    X_nutrient, y_nutrient, test_size=0.2, random_state=42
)

nutrient_model = RandomForestRegressor(n_estimators=300, random_state=42)
nutrient_model.fit(X_train, y_train)

print("Nutrient model trained")

joblib.dump(nutrient_model,"nutrient_model.pkl")
joblib.dump(soil_encoder,"soil_encoder.pkl")

"""# Step 4 — Model 2 (NPK ➜ Crop)"""

from sklearn.ensemble import RandomForestClassifier

X_crop = df[['Nitrogen','Phosphorous','Potassium']]
y_crop = df['Crop_Enc']

X_train, X_test, y_train, y_test = train_test_split(
    X_crop, y_crop, test_size=0.2, random_state=42
)

crop_model = RandomForestClassifier(n_estimators=300, random_state=42)
crop_model.fit(X_train, y_train)

print("Crop model trained")

joblib.dump(crop_model,"crop_model.pkl")
joblib.dump(crop_encoder,"crop_encoder.pkl")

"""# Step 5 — Model 3 (NPK ➜ Fertilizer)"""

X_fert = df[['Nitrogen','Phosphorous','Potassium']]
y_fert = df['Fert_Enc']

X_train, X_test, y_train, y_test = train_test_split(
    X_fert, y_fert, test_size=0.2, random_state=42
)

fert_model = RandomForestClassifier(n_estimators=300, random_state=42)
fert_model.fit(X_train, y_train)

print("Fertilizer model trained")

joblib.dump(fert_model,"fertilizer_model.pkl")
joblib.dump(fert_encoder,"fert_encoder.pkl") 